apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-catalog-sar-creator-binding
roleRef:
  kind: ClusterRole
  name: sar-creator
subjects:
- kind: ServiceAccount
  name: service-catalog-apiserver
  namespace: kube-service-catalog
