apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-catalog-controller-binding
roleRef:
  kind: ClusterRole
  name: service-catalog-controller
subjects:
- kind: ServiceAccount
  name: service-catalog-controller
  namespace: kube-service-catalog
