apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-info-configmap
  namespace: kube-service-catalog
rules:
- apiGroups:     [""]
  resources:     ["configmaps"]
  resourceNames: ["cluster-info"]
  verbs:         ["get","create","list","watch","update"]
