apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-info-configmap-binding
  namespace: kube-service-catalog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-info-configmap
subjects:
- kind: ServiceAccount
  namespace: kube-service-catalog
  name: service-catalog-controller
