apiVersion: v1
kind: Service
metadata:
  namespace: kube-service-catalog
  name: api
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    app: apiserver
  ports:
  - name: https
    port: 443
    targetPort: 6443
